<?php
namespace Saltus\WP\Plugin\Saltus\InteractiveMaps\Plugin;

/**
 * Defines the list of available maps
 */
class MapList {

	public $maps;

	public function __construct() {
		$this->set_maps();
	}

	public function set_maps() {
		$json = '{
			"Kartenset NRW":{
				"custom_seabokas_germanyNordrheinWestfalen":"Deutschland - Nordrhein-Westfalen (NRW) (27mb)",
				"custom_seabokas_germanyRegierungsbezirkKoeln":"Deutschland - NRW - Regierungsbezirk Köln (6.9mb)",
				"custom_seabokas_germanyRegierungsbezirkArnsberg":"Deutschland - NRW - Regierungsbezirk Arnsberg (6.6mb)",
				"custom_seabokas_germanyRegierungsbezirkDetmold":"Deutschland - NRW - Regierungsbezirk Detmold (4.1mb)",
				"custom_seabokas_germanyRegierungsbezirkDuesseldorf":"Deutschland - NRW - Regierungsbezirk Düsseldorf (5.1mb)",
				"custom_seabokas_germanyRegierungsbezirkMuenster":"Deutschland - NRW - Regierungsbezirk Münster (4mb)",
				"custom_seabokas_germanyGelsenkirchenStadtteile":"Deutschland - Gelsenkirchen Stadtteile (23kb)"
			},
			"Portugal Maps":{
				"custom_cmoreira_portugalLisboaFreguesias":"Portugal - Freguesias Lisboa (23kb)",
				"custom_cmoreira_portugalPortoFreguesias":"Portugal - Freguesias Porto (12kb)",
				"custom_cmoreira_portugalModifiedDistricts":"Portugal - Districts Viewport (73kb)",
				"custom_cmoreira_portugalModifiedMunicipios":"Portugal -  Municipios Viewport (369kb)"
			},
			"Countries":{
			   "albaniaHigh":"Albania High (37kb)",
			   "albaniaLow":"Albania Low (16kb)",
			   "algeriaHigh":"Algeria High (127kb)",
			   "algeriaLow":"Algeria Low (55kb)",
			   "americanSamoaHigh":"American Samoa High (44kb)",
			   "americanSamoaLow":"American Samoa Low (17kb)",
			   "andorraHigh":"Andorra High (19kb)",
			   "andorraLow":"Andorra Low (8kb)",
			   "angolaHigh":"Angola High (69kb)",
			   "angolaLow":"Angola Low (30kb)",
			   "anguillaHigh":"Anguilla High (51kb)",
			   "anguillaLow":"Anguilla Low (24kb)",
			   "antiguaBarbudaHigh":"Antigua Barbuda High (39kb)",
			   "antiguaBarbudaLow":"Antigua Barbuda Low (17kb)",
			   "argentinaHigh":"Argentina High (77kb)",
			   "argentinaLow":"Argentina Low (33kb)",
			   "armeniaHigh":"Armenia High (24kb)",
			   "armeniaLow":"Armenia Low (11kb)",
			   "arubaHigh":"Aruba High (11kb)",
			   "arubaLow":"Aruba Low (4kb)",
			   "australiaHigh":"Australia High (43kb)",
			   "australiaLow":"Australia Low (18kb)",
			   "austriaHigh":"Austria High (181kb)",
			   "austriaLow":"Austria Low (70kb)",
			   "azerbaijanHigh":"Azerbaijan High (178kb)",
			   "azerbaijanLow":"Azerbaijan Low (79kb)",
			   "bahrainHigh":"Bahrain High (34kb)",
			   "bahrainLow":"Bahrain Low (14kb)",
			   "bangladeshHigh":"Bangladesh High (60kb)",
			   "bangladeshLow":"Bangladesh Low (25kb)",
			   "barbadosHigh":"Barbados High (18kb)",
			   "barbadosLow":"Barbados Low (9kb)",
			   "belarusHigh":"Belarus High (55kb)",
			   "belarusLow":"Belarus Low (21kb)",
			   "belgiumHigh":"Belgium High (151kb)",
			   "belgiumLow":"Belgium Low (58kb)",
			   "belizeHigh":"Belize High (61kb)",
			   "belizeLow":"Belize Low (24kb)",
			   "beninHigh":"Benin High (78kb)",
			   "beninLow":"Benin Low (31kb)",
			   "bermudaHigh":"Bermuda High (39kb)",
			   "bermudaLow":"Bermuda Low (17kb)",
			   "bhutanHigh":"Bhutan High (50kb)",
			   "bhutanLow":"Bhutan Low (22kb)",
			   "boliviaHigh":"Bolivia High (20kb)",
			   "boliviaLow":"Bolivia Low (9kb)",
			   "bonaireSintEustatiusSabaHigh":"Bonaire Sint Eustatius Saba High (5kb)",
			   "bonaireSintEustatiusSabaLow":"Bonaire Sint Eustatius Saba Low (2kb)",
			   "bosniaHerzegovinaCantonsHigh":"Bosnia Herzegovina Cantons High (27kb)",
			   "bosniaHerzegovinaCantonsLow":"Bosnia Herzegovina Cantons Low (13kb)",
			   "bosniaHerzegovinaHigh":"Bosnia Herzegovina High (17kb)",
			   "bosniaHerzegovinaLow":"Bosnia Herzegovina Low (7kb)",
			   "botswanaHigh":"Botswana High (54kb)",
			   "botswanaLow":"Botswana Low (21kb)",
			   "brazilHigh":"Brazil High (93kb)",
			   "brazilLow":"Brazil Low (40kb)",
			   "bruneiDarussalamHigh":"Brunei Darussalam High (17kb)",
			   "bruneiDarussalamLow":"Brunei Darussalam Low (7kb)",
			   "bulgariaHigh":"Bulgaria High (88kb)",
			   "bulgariaLow":"Bulgaria Low (38kb)",
			   "burkinaFasoHigh":"Burkina Faso High (33kb)",
			   "burkinaFasoLow":"Burkina Faso Low (15kb)",
			   "burundiHigh":"Burundi High (73kb)",
			   "burundiLow":"Burundi Low (31kb)",
			   "cambodiaHigh":"Cambodia High (2mb)",
			   "cambodiaLow":"Cambodia Low (688kb)",
			   "cameroonHigh":"Cameroon High (59kb)",
			   "cameroonLow":"Cameroon Low (27kb)",
			   "canadaHigh":"Canada High (223kb)",
			   "canadaLow":"Canada Low (89kb)",
			   "capeVerdeHigh":"Cape Verde High (41kb)",
			   "capeVerdeLow":"Cape Verde Low (20kb)",
			   "centralAfricanRepublicHigh":"Central African Republic High (53kb)",
			   "centralAfricanRepublicLow":"Central African Republic Low (23kb)",
			   "chadHigh":"Chad High (26kb)",
			   "chadLow":"Chad Low (14kb)",
			   "channelIslandsHigh":"Channel Islands High (38kb)",
			   "channelIslandsLow":"Channel Islands Low (27kb)",
			   "chileHigh":"Chile High (114kb)",
			   "chileLow":"Chile Low (49kb)",
			   "chinaHigh":"China High (201kb)",
			   "chinaLow":"China Low (81kb)",
			   "colombiaHigh":"Colombia High (73kb)",
			   "colombiaLow":"Colombia Low (33kb)",
			   "colombiaMuniHigh":"Colombia Muni High (2mb)",
			   "colombiaMuniLow":"Colombia Muni Low (922kb)",
			   "congoDRHigh":"Congo D R High (90kb)",
			   "congoDRLow":"Congo D R Low (39kb)",
			   "congoHigh":"Congo High (57kb)",
			   "congoLow":"Congo Low (23kb)",
			   "costaRicaHigh":"Costa Rica High (48kb)",
			   "costaRicaLow":"Costa Rica Low (21kb)",
			   "croatiaHigh":"Croatia High (61kb)",
			   "croatiaLow":"Croatia Low (27kb)",
			   "curacaoHigh":"Curacao High (1kb)",
			   "curacaoLow":"Curacao Low (618bb)",
			   "cyprusHigh":"Cyprus High (30kb)",
			   "cyprusLow":"Cyprus Low (12kb)",
			   "cyprusNorthCyprusHigh":"Cyprus North Cyprus High (43kb)",
			   "cyprusNorthCyprusLow":"Cyprus North Cyprus Low (19kb)",
			   "czechRepublicHigh":"Czech Republic High (301kb)",
			   "czechRepublicLow":"Czech Republic Low (112kb)",
			   "czechiaHigh":"Czechia High (301kb)",
			   "czechiaLow":"Czechia Low (112kb)",
			   "denmarkHigh":"Denmark High (73kb)",
			   "denmarkLow":"Denmark Low (29kb)",
			   "djiboutiHigh":"Djibouti High (13kb)",
			   "djiboutiLow":"Djibouti Low (6kb)",
			   "dominicaHigh":"Dominica High (76kb)",
			   "dominicaLow":"Dominica Low (33kb)",
			   "dominicanRepublicHigh":"Dominican Republic High (76kb)",
			   "dominicanRepublicLow":"Dominican Republic Low (35kb)",
			   "dominicanRepublicMuniHigh":"Dominican Republic Muni High (940kb)",
			   "dominicanRepublicMuniLow":"Dominican Republic Muni Low (289kb)",
			   "ecuadorHigh":"Ecuador High (93kb)",
			   "ecuadorLow":"Ecuador Low (39kb)",
			   "egyptHigh":"Egypt High (108kb)",
			   "egyptLow":"Egypt Low (53kb)",
			   "elSalvadorHigh":"EL Salvador High (59kb)",
			   "elSalvadorLow":"EL Salvador Low (26kb)",
			   "equatorialGuineaHigh":"Equatorial Guinea High (797kb)",
			   "equatorialGuineaLow":"Equatorial Guinea Low (287kb)",
			   "estoniaHigh":"Estonia High (96kb)",
			   "estoniaLow":"Estonia Low (40kb)",
			   "eswatiniHigh":"Eswatini High (40kb)",
			   "eswatiniLow":"Eswatini Low (18kb)",
			   "faroeIslandsHigh":"Faroe Islands High (9kb)",
			   "faroeIslandsLow":"Faroe Islands Low (4kb)",
			   "fijiEastHigh":"Fiji East High (5kb)",
			   "fijiEastLow":"Fiji East Low (2kb)",
			   "fijiWestHigh":"Fiji West High (24kb)",
			   "fijiWestLow":"Fiji West Low (10kb)",
			   "finlandHigh":"Finland High (169kb)",
			   "finlandLow":"Finland Low (74kb)",
			   "franceDepartmentsHigh":"France Departments High (158kb)",
			   "franceDepartmentsLow":"France Departments Low (76kb)",
			   "franceHigh":"France High (55kb)",
			   "franceLow":"France Low (22kb)",
			   "frenchGuianaHigh":"French Guiana High (28kb)",
			   "frenchGuianaLow":"French Guiana Low (11kb)",
			   "gabonHigh":"Gabon High (212kb)",
			   "gabonLow":"Gabon Low (91kb)",
			   "georgiaHigh":"Georgia High (72kb)",
			   "georgiaLow":"Georgia Low (29kb)",
			   "georgiaSouthOssetiaHigh":"Georgia South Ossetia High (74kb)",
			   "georgiaSouthOssetiaLow":"Georgia South Ossetia Low (31kb)",
			   "germanyHigh":"Germany High (665kb)",
			   "germanyLow":"Germany Low (253kb)",
			   "greeceHigh":"Greece High (106kb)",
			   "greeceLow":"Greece Low (44kb)",
			   "greenlandHigh":"Greenland High (166kb)",
			   "greenlandLow":"Greenland Low (66kb)",
			   "guineaHigh":"Guinea High (43kb)",
			   "guineaLow":"Guinea Low (17kb)",
			   "hondurasHigh":"Honduras High (79kb)",
			   "hondurasLow":"Honduras Low (33kb)",
			   "hongKongHigh":"Hong Kong High (75kb)",
			   "hongKongLow":"Hong Kong Low (33kb)",
			   "hungaryHigh":"Hungary High (54kb)",
			   "hungaryLow":"Hungary Low (24kb)",
			   "icelandHigh":"Iceland High (73kb)",
			   "icelandLow":"Iceland Low (33kb)",
			   "indiaHigh":"India High (170kb)",
			   "indiaLow":"India Low (69kb)",
			   "indonesiaHigh":"Indonesia High (167kb)",
			   "indonesiaLow":"Indonesia Low (71kb)",
			   "irelandHigh":"Ireland High (222kb)",
			   "irelandLow":"Ireland Low (93kb)",
			   "israelHigh":"Israel High (27kb)",
			   "israelLow":"Israel Low (12kb)",
			   "israelPalestineHigh":"Israel Palestine High (49kb)",
			   "israelPalestineLow":"Israel Palestine Low (23kb)",
			   "italyHigh":"Italy High (66kb)",
			   "italyLow":"Italy Low (28kb)",
			   "japanHigh":"Japan High (181kb)",
			   "japanLow":"Japan Low (78kb)",
			   "kazakhstanHigh":"Kazakhstan High (90kb)",
			   "kazakhstanLow":"Kazakhstan Low (40kb)",
			   "kenyaHigh":"Kenya High (4mb)",
			   "kenyaLow":"Kenya Low (1mb)",
			   "kosovoHigh":"Kosovo High (25kb)",
			   "kosovoLow":"Kosovo Low (10kb)",
			   "kyrgyzstanHigh":"Kyrgyzstan High (133kb)",
			   "kyrgyzstanLow":"Kyrgyzstan Low (50kb)",
			   "latviaHigh":"Latvia High (164kb)",
			   "latviaLow":"Latvia Low (82kb)",
			   "liechtensteinHigh":"Liechtenstein High (29kb)",
			   "liechtensteinLow":"Liechtenstein Low (14kb)",
			   "lithuaniaHigh":"Lithuania High (154kb)",
			   "lithuaniaLow":"Lithuania Low (61kb)",
			   "malaysiaHigh":"Malaysia High (86kb)",
			   "malaysiaLow":"Malaysia Low (36kb)",
			   "maldivesHigh":"Maldives High (62kb)",
			   "maldivesIslandsHigh":"Maldives Islands High (499kb)",
			   "maldivesIslandsLow":"Maldives Islands Low (226kb)",
			   "maldivesLow":"Maldives Low (26kb)",
			   "maliHigh":"Mali High (279kb)",
			   "maliLow":"Mali Low (103kb)",
			   "maltaHigh":"Malta High (15kb)",
			   "maltaLow":"Malta Low (7kb)",
			   "mexicoHigh":"Mexico High (180kb)",
			   "mexicoLow":"Mexico Low (76kb)",
			   "moldovaHigh":"Moldova High (45kb)",
			   "moldovaLow":"Moldova Low (24kb)",
			   "mongoliaHigh":"Mongolia High (160kb)",
			   "mongoliaLow":"Mongolia Low (71kb)",
			   "moroccoHigh":"Morocco High (196kb)",
			   "moroccoLow":"Morocco Low (87kb)",
			   "namibiaHigh":"Namibia High (53kb)",
			   "namibiaLow":"Namibia Low (24kb)",
			   "nepalHigh":"Nepal High (34kb)",
			   "nepalLow":"Nepal Low (14kb)",
			   "netherlandsHigh":"Netherlands High (123kb)",
			   "netherlandsLow":"Netherlands Low (49kb)",
			   "newZealandHigh":"New Zealand High (176kb)",
			   "newZealandLow":"New Zealand Low (71kb)",
			   "nicaraguaHigh":"Nicaragua High (79kb)",
			   "nicaraguaLow":"Nicaragua Low (35kb)",
			   "nigeriaHigh":"Nigeria High (83kb)",
			   "nigeriaLow":"Nigeria Low (39kb)",
			   "northKoreaHigh":"North Korea High (170kb)",
			   "northKoreaLow":"North Korea Low (74kb)",
			   "norwayHigh":"Norway High (301kb)",
			   "norwayLow":"Norway Low (125kb)",
			   "omanHigh":"Oman High (74kb)",
			   "omanLow":"Oman Low (33kb)",
			   "pakistanHigh":"Pakistan High (39kb)",
			   "pakistanLow":"Pakistan Low (16kb)",
			   "palestineHigh":"Palestine High (37kb)",
			   "palestineLow":"Palestine Low (17kb)",
			   "panamaHigh":"Panama High (53kb)",
			   "panamaLow":"Panama Low (23kb)",
			   "peruHigh":"Peru High (69kb)",
			   "peruLow":"Peru Low (31kb)",
			   "philippinesHigh":"Philippines High (117kb)",
			   "philippinesLow":"Philippines Low (58kb)",
			   "polandHigh":"Poland High (411kb)",
			   "polandLow":"Poland Low (161kb)",
			   "portugalHigh":"Portugal High (44kb)",
			   "portugalLow":"Portugal Low (20kb)",
			   "portugalRegionsHigh":"Portugal Regions High (29kb)",
			   "portugalRegionsLow":"Portugal Regions Low (12kb)",
			   "puertoRicoHigh":"Puerto Rico High (480kb)",
			   "puertoRicoLow":"Puerto Rico Low (223kb)",
			   "qatarHigh":"Qatar High (36kb)",
			   "qatarLow":"Qatar Low (16kb)",
			   "romaniaHigh":"Romania High (182kb)",
			   "romaniaLow":"Romania Low (76kb)",
			   "russiaCrimeaHigh":"Russia Crimea High (1mb)",
			   "russiaCrimeaLow":"Russia Crimea Low (223kb)",
			   "russiaHigh":"Russia High (1mb)",
			   "russiaLow":"Russia Low (223kb)",
			   "saintHelenaHigh":"Saint Helena High (86kb)",
			   "saintHelenaLow":"Saint Helena Low (34kb)",
			   "saintLuciaHigh":"Saint Lucia High (56kb)",
			   "saintLuciaLow":"Saint Lucia Low (22kb)",
			   "saintVincentHigh":"Saint Vincent High (34kb)",
			   "saintVincentLow":"Saint Vincent Low (15kb)",
			   "samoaHigh":"Samoa High (31kb)",
			   "samoaLow":"Samoa Low (15kb)",
			   "sanMarinoHigh":"San Marino High (21kb)",
			   "sanMarinoLow":"San Marino Low (10kb)",
			   "saoTomePrincipeHigh":"Sao Tome Principe High (21kb)",
			   "saoTomePrincipeLow":"Sao Tome Principe Low (10kb)",
			   "saudiArabiaHigh":"Saudi Arabia High (72kb)",
			   "saudiArabiaLow":"Saudi Arabia Low (30kb)",
			   "senegalHigh":"Senegal High (120kb)",
			   "senegalLow":"Senegal Low (50kb)",
			   "serbiaHigh":"Serbia High (54kb)",
			   "serbiaLow":"Serbia Low (27kb)",
			   "serbiaNoKosovoHigh":"Serbia No Kosovo High (47kb)",
			   "serbiaNoKosovoLow":"Serbia No Kosovo Low (23kb)",
			   "seychellesHigh":"Seychelles High (130kb)",
			   "seychellesLow":"Seychelles Low (57kb)",
			   "singaporeHigh":"Singapore High (82kb)",
			   "singaporeLow":"Singapore Low (33kb)",
			   "slovakiaHigh":"Slovakia High (119kb)",
			   "slovakiaLow":"Slovakia Low (46kb)",
			   "sloveniaHigh":"Slovenia High (4mb)",
			   "sloveniaLow":"Slovenia Low (2mb)",
			   "sloveniaRegionsHigh":"Slovenia Regions High (1mb)",
			   "sloveniaRegionsLow":"Slovenia Regions Low (540kb)",
			   "solomonIslandsHigh":"Solomon Islands High (384kb)",
			   "solomonIslandsLow":"Solomon Islands Low (146kb)",
			   "somaliaHigh":"Somalia High (43kb)",
			   "somaliaLow":"Somalia Low (20kb)",
			   "southAfricaHigh":"South Africa High (56kb)",
			   "southAfricaLow":"South Africa Low (23kb)",
			   "southKoreaHigh":"South Korea High (254kb)",
			   "southKoreaLow":"South Korea Low (108kb)",
			   "spainHigh":"Spain High (194kb)",
			   "spainLow":"Spain Low (76kb)",
			   "spainProvincesHigh":"Spain Provinces High (474kb)",
			   "spainProvincesLow":"Spain Provinces Low (284kb)",
			   "sriLankaHigh":"Sri Lanka High (75kb)",
			   "sriLankaLow":"Sri Lanka Low (34kb)",
			   "stKittsNevisHigh":"ST Kitts Nevis High (18kb)",
			   "stKittsNevisLow":"ST Kitts Nevis Low (10kb)",
			   "stPierreMiquelonHigh":"ST Pierre Miquelon High (18kb)",
			   "stPierreMiquelonLow":"ST Pierre Miquelon Low (7kb)",
			   "sudanHigh":"Sudan High (44kb)",
			   "sudanLow":"Sudan Low (21kb)",
			   "svalbardHigh":"Svalbard High (162kb)",
			   "svalbardLow":"Svalbard Low (62kb)",
			   "swedenHigh":"Sweden High (74kb)",
			   "swedenLow":"Sweden Low (32kb)",
			   "switzerlandHigh":"Switzerland High (175kb)",
			   "switzerlandLow":"Switzerland Low (70kb)",
			   "syriaHigh":"Syria High (28kb)",
			   "syriaLow":"Syria Low (13kb)",
			   "tajikistanHigh":"Tajikistan High (56kb)",
			   "tajikistanLow":"Tajikistan Low (22kb)",
			   "tanzaniaHigh":"Tanzania High (196kb)",
			   "tanzaniaLow":"Tanzania Low (81kb)",
			   "thailandHigh":"Thailand High (222kb)",
			   "thailandLow":"Thailand Low (97kb)",
			   "tunisiaHigh":"Tunisia High (60kb)",
			   "tunisiaLow":"Tunisia Low (27kb)",
			   "turkeyHigh":"Turkey High (437kb)",
			   "turkeyLow":"Turkey Low (183kb)",
			   "uaeHigh":"Uae High (58kb)",
			   "uaeLow":"Uae Low (26kb)",
			   "ukCountiesHigh":"UK Counties High (87kb)",
			   "ukCountiesLow":"UK Counties Low (41kb)",
			   "ukHigh":"UK High (641kb)",
			   "ukLow":"UK Low (274kb)",
			   "ukraineHigh":"Ukraine High (239kb)",
			   "ukraineLow":"Ukraine Low (93kb)",
			   "usaAlbersHigh":"Usa Albers High (208kb)",
			   "usaAlbersLow":"Usa Albers Low (90kb)",
			   "usaHigh":"Usa High (184kb)",
			   "usaLow":"Usa Low (80kb)",
			   "usaTerritories2High":"Usa Territories2 High (240kb)",
			   "usaTerritories2Low":"Usa Territories2 Low (104kb)",
			   "usaTerritoriesHigh":"Usa Territories High (204kb)",
			   "usaTerritoriesLow":"Usa Territories Low (88kb)",
			   "uzbekistanHigh":"Uzbekistan High (46kb)",
			   "uzbekistanLow":"Uzbekistan Low (21kb)",
			   "vaticanHigh":"Vatican High (2kb)",
			   "vaticanLow":"Vatican Low (771bb)",
			   "venezuelaHigh":"Venezuela High (65kb)",
			   "venezuelaLow":"Venezuela Low (30kb)",
			   "vietnamHigh":"Vietnam High (252kb)",
			   "vietnamLow":"Vietnam Low (108kb)",
			   "yemenHigh":"Yemen High (56kb)",
			   "yemenLow":"Yemen Low (28kb)",
			   "zambiaHigh":"Zambia High (77kb)",
			   "zambiaLow":"Zambia Low (31kb)",
			   "zimbabweHigh":"Zimbabwe High (63kb)",
			   "zimbabweLow":"Zimbabwe Low (25kb)"
			},
			"USA":{
			   "region\/usa\/akAlbersHigh":"Alaska Albers High (783kb)",
			   "region\/usa\/akAlbersLow":"Alaska Albers Low (278kb)",
			   "region\/usa\/akHigh":"Alaska High (701kb)",
			   "region\/usa\/akLow":"Alaska Low (249kb)",
			   "region\/usa\/alHigh":"Alabama High (77kb)",
			   "region\/usa\/alLow":"Alabama Low (38kb)",
			   "region\/usa\/arHigh":"Arkansas High (83kb)",
			   "region\/usa\/arLow":"Arkansas Low (41kb)",
			   "region\/usa\/azHigh":"Arizona High (39kb)",
			   "region\/usa\/azLow":"Arizona Low (16kb)",
			   "region\/usa\/caHigh":"California High (158kb)",
			   "region\/usa\/caLow":"California Low (64kb)",
			   "region\/usa\/coHigh":"Colorado High (64kb)",
			   "region\/usa\/coLow":"Colorado Low (33kb)",
			   "region\/usa\/ctHigh":"Connecticut High (10kb)",
			   "region\/usa\/ctLow":"Connecticut Low (5kb)",
			   "region\/usa\/dcHigh":"District of Columbia High (735bb)",
			   "region\/usa\/dcLow":"District of Columbia Low (431bb)",
			   "region\/usa\/deHigh":"Delaware High (6kb)",
			   "region\/usa\/deLow":"Delaware Low (2kb)",
			   "region\/usa\/flHigh":"Florida High (149kb)",
			   "region\/usa\/flLow":"Florida Low (65kb)",
			   "region\/usa\/gaHigh":"Georgia High (396kb)",
			   "region\/usa\/gaLow":"Georgia Low (161kb)",
			   "region\/usa\/hiAlbersHigh":"Hawaii Albers High (26kb)",
			   "region\/usa\/hiAlbersLow":"Hawaii Albers Low (10kb)",
			   "region\/usa\/hiHigh":"Hawaii High (9kb)",
			   "region\/usa\/hiLow":"Hawaii Low (4kb)",
			   "region\/usa\/iaHigh":"Iowa High (44kb)",
			   "region\/usa\/iaLow":"Iowa Low (31kb)",
			   "region\/usa\/idHigh":"Idaho High (84kb)",
			   "region\/usa\/idLow":"Idaho Low (36kb)",
			   "region\/usa\/ilHigh":"Illinois High (71kb)",
			   "region\/usa\/ilLow":"Illinois Low (42kb)",
			   "region\/usa\/inHigh":"Indiana High (53kb)",
			   "region\/usa\/inLow":"Indiana Low (34kb)",
			   "region\/usa\/ksHigh":"Kansas High (38kb)",
			   "region\/usa\/ksLow":"Kansas Low (32kb)",
			   "region\/usa\/kyHigh":"Kentuchy High (108kb)",
			   "region\/usa\/kyLow":"Kentuchy Low (57kb)",
			   "region\/usa\/laHigh":"Louisiana High (150kb)",
			   "region\/usa\/laLow":"Louisiana Low (65kb)",
			   "region\/usa\/maHigh":"Massachusetts High (23kb)",
			   "region\/usa\/maLow":"Massachusetts Low (10kb)",
			   "region\/usa\/mdHigh":"Maryland High (65kb)",
			   "region\/usa\/mdLow":"Maryland Low (27kb)",
			   "region\/usa\/meHigh":"Maine High (58kb)",
			   "region\/usa\/meLow":"Maine Low (24kb)",
			   "region\/usa\/miHigh":"Michigan High (76kb)",
			   "region\/usa\/miLow":"Michigan Low (40kb)",
			   "region\/usa\/mnHigh":"Minnesota High (75kb)",
			   "region\/usa\/mnLow":"Minnesota Low (42kb)",
			   "region\/usa\/moHigh":"Missouri High (105kb)",
			   "region\/usa\/moLow":"Missouri Low (56kb)",
			   "region\/usa\/msHigh":"Mississippi High (56kb)",
			   "region\/usa\/msLow":"Mississippi Low (34kb)",
			   "region\/usa\/mtHigh":"Montana High (97kb)",
			   "region\/usa\/mtLow":"Montana Low (43kb)",
			   "region\/usa\/ncHigh":"North Carolina High (147kb)",
			   "region\/usa\/ncLow":"North Carolina Low (70kb)",
			   "region\/usa\/ndHigh":"North Dakota High (50kb)",
			   "region\/usa\/ndLow":"North Dakota Low (27kb)",
			   "region\/usa\/neHigh":"Nebraska High (41kb)",
			   "region\/usa\/neLow":"Nebraska Low (30kb)",
			   "region\/usa\/nhHigh":"New Hampshire High (17kb)",
			   "region\/usa\/nhLow":"New Hampshire Low (8kb)",
			   "region\/usa\/njHigh":"New Jersey High (36kb)",
			   "region\/usa\/njLow":"New Jersey Low (16kb)",
			   "region\/usa\/nmHigh":"New Mexico High (29kb)",
			   "region\/usa\/nmLow":"New Mexico Low (16kb)",
			   "region\/usa\/nvHigh":"Nevada High (25kb)",
			   "region\/usa\/nvLow":"Nevada Low (11kb)",
			   "region\/usa\/nyHigh":"New York High (65kb)",
			   "region\/usa\/nyLow":"New York Low (34kb)",
			   "region\/usa\/ohHigh":"Ohio High (49kb)",
			   "region\/usa\/ohLow":"Ohio Low (33kb)",
			   "region\/usa\/okHigh":"Oklahoma High (51kb)",
			   "region\/usa\/okLow":"Oklahoma Low (31kb)",
			   "region\/usa\/orHigh":"Oregon High (96kb)",
			   "region\/usa\/orLow":"Oregon Low (40kb)",
			   "region\/usa\/paHigh":"Pennsylvania High (89kb)",
			   "region\/usa\/paLow":"Pennsylvania Low (41kb)",
			   "region\/usa\/riHigh":"Rhode Island High (5kb)",
			   "region\/usa\/riLow":"Rhode Island Low (3kb)",
			   "region\/usa\/scHigh":"South Carolina High (69kb)",
			   "region\/usa\/scLow":"South Carolina Low (32kb)",
			   "region\/usa\/sdHigh":"South Dakota High (44kb)",
			   "region\/usa\/sdLow":"South Dakota Low (27kb)",
			   "region\/usa\/tnHigh":"Tennessee High (85kb)",
			   "region\/usa\/tnLow":"Tennessee Low (45kb)",
			   "region\/usa\/txHigh":"Texas High (227kb)",
			   "region\/usa\/txLow":"Texas Low (124kb)",
			   "region\/usa\/usaCountiesHigh":"Usa Counties High (2mb)",
			   "region\/usa\/usaCountiesLow":"Usa Counties Low (1mb)",
			   "region\/usa\/utHigh":"Utah High (48kb)",
			   "region\/usa\/utLow":"Utah Low (21kb)",
			   "region\/usa\/vaHigh":"Virginia High (158kb)",
			   "region\/usa\/vaLow":"Virginia Low (78kb)",
			   "region\/usa\/vtHigh":"Vermont High (18kb)",
			   "region\/usa\/vtLow":"Vermont Low (9kb)",
			   "region\/usa\/waHigh":"Washington High (102kb)",
			   "region\/usa\/waLow":"Washington Low (43kb)",
			   "region\/usa\/wiHigh":"Wisconsin High (60kb)",
			   "region\/usa\/wiLow":"Wisconsin Low (33kb)",
			   "region\/usa\/wvHigh":"West Virginia High (80kb)",
			   "region\/usa\/wvLow":"West Virginia Low (36kb)",
			   "region\/usa\/wyHigh":"Wyoming High (22kb)",
			   "region\/usa\/wyLow":"Wyoming Low (12kb)"
			},
			"World & Continents":{
			   "region\/world\/africaHigh":"Africa High (79kb)",
			   "region\/world\/africaLow":"Africa Low (37kb)",
			   "region\/world\/africaUltra":"Africa Ultra (185kb)",
			   "region\/world\/asiaHigh":"Asia High (161kb)",
			   "region\/world\/asiaLow":"Asia Low (63kb)",
			   "region\/world\/asiaUltra":"Asia Ultra (403kb)",
			   "region\/world\/caribbeanHigh":"Caribbean High (13kb)",
			   "region\/world\/caribbeanLow":"Caribbean Low (9kb)",
			   "region\/world\/caribbeanUltra":"Caribbean Ultra (24kb)",
			   "region\/world\/centralAmericaHigh":"Central America High (13kb)",
			   "region\/world\/centralAmericaLow":"Central America Low (5kb)",
			   "region\/world\/europeHigh":"Europe High (106kb)",
			   "region\/world\/europeLow":"Europe Low (45kb)",
			   "region\/world\/europeUltra":"Europe Ultra (253kb)",
			   "region\/world\/latinAmericaHigh":"Latin America High (78kb)",
			   "region\/world\/latinAmericaLow":"Latin America Low (34kb)",
			   "region\/world\/latinAmericaUltra":"Latin America Ultra (185kb)",
			   "region\/world\/middleEastHigh":"Middle East High (16kb)",
			   "region\/world\/middleEastLow":"Middle East Low (7kb)",
			   "region\/world\/middleEastUltra":"Middle East Ultra (36kb)",
			   "region\/world\/northAmericaHigh":"North America High (141kb)",
			   "region\/world\/northAmericaLow":"North America Low (55kb)",
			   "region\/world\/northAmericaUltra":"North America Ultra (351kb)",
			   "region\/world\/oceaniaHigh":"Oceania High (52kb)",
			   "region\/world\/oceaniaLow":"Oceania Low (20kb)",
			   "region\/world\/oceaniaUltra":"Oceania Ultra (128kb)",
			   "region\/world\/southAmericaHigh":"South America High (51kb)",
			   "region\/world\/southAmericaLow":"South America Low (20kb)",
			   "region\/world\/southAmericaUltra":"South America Ultra (130kb)",
			   "unRegionsHigh":"UN Regions High (380kb)",
			   "unRegionsLow":"UN Regions Low (133kb)",
			   "region\/world\/worldRegionsHigh":"World Regions High (357kb)",
			   "region\/world\/worldRegionsLow":"World Regions Low (121kb)",
			   "region\/world\/worldRegionsUltra":"World Regions Ultra (935kb)",
			   "worldHigh":"World High (603kb)",
			   "worldIndiaHigh":"World India High (604kb)",
			   "worldIndiaLow":"World India Low (245kb)",
			   "worldIndiaUltra":"World India Ultra (1mb)",
			   "worldLow":"World Low (244kb)",
			   "worldUltra":"World Ultra (1mb)",
			   "continentsHigh":"Continents High (351kb)",
			   "continentsLow":"Continents Low (118kb)",
			   "continentsRussiaAsiaHigh":"Continents Russia Asia High (355kb)",
			   "continentsRussiaAsiaLow":"Continents Russia Asia Low (120kb)",
			   "continentsRussiaAsiaUltra":"Continents Russia Asia Ultra (931kb)",
			   "continentsRussiaEuropeHigh":"Continents Russia Europe High (363kb)",
			   "continentsRussiaEuropeLow":"Continents Russia Europe Low (123kb)",
			   "continentsRussiaEuropeUltra":"Continents Russia Europe Ultra (952kb)",
			   "continentsUltra":"Continents Ultra (924kb)"
			}
		 }';

		$this->maps = apply_filters( 'igm_map_list', $json );
	}
}
